/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrintersSettingsRouteImport } from './routes/printers-settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as IssueRouteImport } from './routes/issue'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as CostControlRouteImport } from './routes/cost-control'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintersSettingsRoute = PrintersSettingsRouteImport.update({
  id: '/printers-settings',
  path: '/printers-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueRoute = IssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const CostControlRoute = CostControlRouteImport.update({
  id: '/cost-control',
  path: '/cost-control',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cost-control': typeof CostControlRoute
  '/entry': typeof EntryRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/issue': typeof IssueRoute
  '/orders': typeof OrdersRoute
  '/printers-settings': typeof PrintersSettingsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cost-control': typeof CostControlRoute
  '/entry': typeof EntryRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/issue': typeof IssueRoute
  '/orders': typeof OrdersRoute
  '/printers-settings': typeof PrintersSettingsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cost-control': typeof CostControlRoute
  '/entry': typeof EntryRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/issue': typeof IssueRoute
  '/orders': typeof OrdersRoute
  '/printers-settings': typeof PrintersSettingsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/cost-control'
    | '/entry'
    | '/history'
    | '/inventory'
    | '/issue'
    | '/orders'
    | '/printers-settings'
    | '/reports'
    | '/roles'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/cost-control'
    | '/entry'
    | '/history'
    | '/inventory'
    | '/issue'
    | '/orders'
    | '/printers-settings'
    | '/reports'
    | '/roles'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/cost-control'
    | '/entry'
    | '/history'
    | '/inventory'
    | '/issue'
    | '/orders'
    | '/printers-settings'
    | '/reports'
    | '/roles'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  CostControlRoute: typeof CostControlRoute
  EntryRoute: typeof EntryRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  IssueRoute: typeof IssueRoute
  OrdersRoute: typeof OrdersRoute
  PrintersSettingsRoute: typeof PrintersSettingsRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printers-settings': {
      id: '/printers-settings'
      path: '/printers-settings'
      fullPath: '/printers-settings'
      preLoaderRoute: typeof PrintersSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue': {
      id: '/issue'
      path: '/issue'
      fullPath: '/issue'
      preLoaderRoute: typeof IssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-control': {
      id: '/cost-control'
      path: '/cost-control'
      fullPath: '/cost-control'
      preLoaderRoute: typeof CostControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  CostControlRoute: CostControlRoute,
  EntryRoute: EntryRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  IssueRoute: IssueRoute,
  OrdersRoute: OrdersRoute,
  PrintersSettingsRoute: PrintersSettingsRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
